# Generated by Django 2.0 on 2020-09-01 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artilog',
            fields=[
                ('artilog_id', models.IntegerField(primary_key=True, serialize=False)),
                ('is_published', models.BooleanField()),
                ('artilog_head', models.CharField(max_length=500, null=True)),
                ('artilog_summary', models.CharField(max_length=500, null=True)),
                ('artilog_text', models.TextField(max_length=5000, null=True)),
                ('artilog_date', models.DateField()),
                ('artilog_image_url', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='artilog',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User'),
        ),
    ]
